### ISSUE TITLE
Version 0.20

### ISSUE THREAD

**Issue by zeux** [zeux/meshoptimizer#623]
This is a tracking issue for the next meshoptimizer / gltfpack release, tentatively planned for some time in November. The release so far is already fairly full but there might be a couple more things that would make sense to do.

Improvements: (neither exhaustive nor guaranteed)

- [x] Mark JS `simplifyPoints` and `simplifyWithAttributes` experimental somehow. #627
- [x] Look further into #522; it would be nice to have some sort of solution as part of this release
- [x] ~Look into a possible automatic fix for #433~ -- this can be worked around with  `-vpf`, and fully solving this requires invasive (and therefore risky) changes to gltfpack
- [x] https://github.com/zeux/meshoptimizer/issues/628 needs a documentation and/or code resolution plus JS limits
- [x] gltfpack fuzzing code and fixes
- [x] Update cgltf

Administrative:

- [x] Bump version
- [x] GitHub release
- [x] npm release
